# Generated by Django 4.0.6 on 2022-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
